sonar.projectKey=task-management-tool
sonar.projectName=Task Management Tool
sonar.sourceEncoding=UTF-8
sonar.sources=BackEnd/TaskManagement.Api,FrontEnd/src
sonar.tests=BackEnd/TaskManagement.Tests
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/dist/**
sonar.cs.opencover.reportsPaths=BackEnd/TaskManagement.Tests/TestResults/**/coverage.opencover.xml
sonar.javascript.lcov.reportPaths=FrontEnd/coverage/lcov.info
